#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port1,           bottomL2,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           bottomL1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           xtrarmL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           xtrarmR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armR1L2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armR2L1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           bottomR1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          bottomR2,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
int D = 70;
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)


// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void drivetrain (int power)
{
	  motor[bottomR1] = power;
	  motor[bottomR2] = power;
	  motor[bottomL1] = power;
	  motor[bottomL2] = power;
}
void left ()
{
	drivetrain(127);
	 wait1Msec(500);
	 drivetrain(0);
	 motor[frontR] = 127;
	 motor[frontL] = 127;
	 wait1Msec(2200);
	 motor[frontR] = 0;
	 motor[frontL] = 0;

	 motor[armR1L2] = 127;
	 motor[armR2L1] = 127;
	 motor[xtrarmL] = 127;
	 motor[xtrarmR] = 127;
	 wait1Msec(2200);

	 motor[bottomR1]= 127;
	 motor[bottomR2]= 127;
	 wait1Msec(500);
	 motor[bottomR1]= 0;
	 motor[bottomR2]= 0;

	 drivetrain(127);
	 wait1Msec(2000);
	 drivetrain(0);

	 motor[frontR] = -127;
	 motor[frontL] = -127;
	 wait1Msec(1300);
	 motor[frontR] = 0;
	 motor[frontL] = 0;

	 drivetrain(-127);
	 wait1Msec(500);
	 drivetrain(0);

	 motor[armR1L2] = -127;
	 motor[armR2L1] = -127;
	 motor[xtrarmL] = -127;
	 motor[xtrarmR] = -127;
	 wait1Msec(200);
	 motor[armR1L2] = 0;
	 motor[armR2L1] = 0;
	 motor[xtrarmL] = 0;
	 motor[xtrarmR] = 0;


	 drivetrain(127);
	 wait1Msec(500);
	 drivetrain(0);

}
void right ()
{
	drivetrain(127);
	 wait1Msec(5000);
	 drivetrain(0);
	 /*motor[frontR] = 127;
	 motor[frontL] = 127;
	 wait1Msec(2200);
	 motor[frontR] = 0;
	 motor[frontL] = 0;

	 motor[armR1L2] = 127;
	 motor[armR2L1] = 127;
	 motor[xtrarmL] = 127;
	 motor[xtrarmR] = 127;
	 wait1Msec(2200);

	 motor[bottomL1]= 127;
	 motor[bottomL2]= 127;
	 wait1Msec(500);
	 motor[bottomL1]= 0;
	 motor[bottomL2]= 0;

	 drivetrain(127);
	 wait1Msec(2000);
	 drivetrain(0);

	 motor[frontR] = -127;
	 motor[frontL] = -127;
	 wait1Msec(1300);
	 motor[frontR] = 0;
	 motor[frontL] = 0;

	 drivetrain(-127);
	 wait1Msec(500);
	 drivetrain(0);

	 motor[armR1L2] = -127;
	 motor[armR2L1] = -127;
	 motor[xtrarmL] = -127;
	 motor[xtrarmR] = -127;
	 wait1Msec(200);
	 motor[armR1L2] = 0;
	 motor[armR2L1] = 0;
	 motor[xtrarmL] = 0;
	 motor[xtrarmR] = 0;


	 drivetrain(127);
	 wait1Msec(500);
	 drivetrain(0);

*/

}
void normal ()
{
	motor[frontL] = 127;
	motor[frontR] = 127;
	wait1Msec(800);
	motor[frontL] = 0;
	motor[frontR] = 0;

	motor[armR1L2] = 127;
	motor[armR2L1] = 127;
	motor[xtrarmL] = 127;
	motor[xtrarmR] = 127;
	wait1Msec(2500);

	drivetrain(127);
	wait1Msec(2300);
	drivetrain(0);

}
void pre_auton()
{
		clearLCDLine(0);
			clearLCDLine(1);
			displayLCDCenteredString(0, "Pre_auton");
			displayLCDCenteredString(1, "starting");
			wait1Msec(200);
			//Clear LCD
		clearLCDLine(0);
		clearLCDLine(1);
		bLCDBacklight = true;
		//Loop while center button is not pressed
		while(nLCDButtons != centerButton)
		{
			//Switch case that allows the user to choose from 4 different options
			switch(count){
			case 0:
				//Display first choice
				displayLCDCenteredString(0, "Right");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button pressed
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count = 2;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			case 1:
				//Display first choice
				displayLCDCenteredString(0, "Left");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button press
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count--;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			case 2:
				//Display first choice
				displayLCDCenteredString(0, "Normal");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button press
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count--;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			default:
				count = 0;
				break;
			}
			}
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous()
{
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice from pre_auton.
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Right");
		displayLCDCenteredString(1, "is running!");
		right();
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Left");
		displayLCDCenteredString(1, "is running!");
		left();
		break;
	case 2:
		displayLCDCenteredString(0, "Normal");
		displayLCDCenteredString(1, "is running!");
		normal();
		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	while(true)
	{
	  motor[bottomR1] = vexRT[Ch2];
	  motor[bottomR2] = vexRT[Ch2];
	  motor[bottomL1] = vexRT[Ch3];
	  motor[bottomL2] = vexRT[Ch3];


  if (vexRT[Btn6U] == 1)
		 {
		   int c = 127;
		   motor[armR1L2] = c; //This motor will lift up with value c
		   motor[armR2L1] = c;
		   motor[xtrarmL] = c;
		   motor[xtrarmR] = c;
		 }
	else if (vexRT[Btn6D] == 1)
		 {
		   int c = -127;

		   motor[armR1L2] = c; //This motor will lift down with value c
		   motor[armR2L1] = c;
		   motor[xtrarmL] = c;
		   motor[xtrarmR] = c;
	   }
	else
     {
       int L = 0;

       motor[armR1L2] = L; //This motor will stop running
       motor[armR2L1] = L;
       motor[xtrarmL] = L;
       motor[xtrarmR] = L;
     }

  if (vexRT[Btn5D] == 1) //Front motor will turn inside
     {
       int y = 127;

       motor[frontR] = y;
       motor[frontL] = y;
     }

  else if (vexRT[Btn5U] == 1) //Front motor will turn outside
     {
       int Y = 127;

       motor[frontR] = -Y;
       motor[frontL] = -Y;
     }

  else // The motor will be stop
  	 {

  	   int L = 0;

  	   motor[frontR] = L;
  	   motor[frontL] = L;
     }

/*  if (vexRT[Btn8U] == 1) // The motors will lock
     {
  	   int H = 20;

  	   motor[frontR] = -H;
  	   motor[frontL] = -H;
     }*/
  }
}
  	// This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.
    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................
    // Remove this function call once you have "real" code.
    //UserControlCodePlaceholderForTesting();
