#pragma config(Sensor, in1,    potlift,        sensorPotentiometer)
#pragma config(Sensor, in2,    potclaw,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  quadleft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  quadright,      sensorQuadEncoder)
#pragma config(Motor,  port1,           driveL3,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveL1L2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driveL4,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armX,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driveR4,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           driveR1R2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          driveR3,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)


// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void left ()
{


}
void right ()
{


}
void normal ()
{


}
void pre_auton()
{
		clearLCDLine(0);
			clearLCDLine(1);
			displayLCDCenteredString(0, "Pre_auton");
			displayLCDCenteredString(1, "starting");
			wait1Msec(200);
			//Clear LCD
		clearLCDLine(0);
		clearLCDLine(1);
		bLCDBacklight = true;
		//Loop while center button is not pressed
		while(nLCDButtons != centerButton)
		{
			//Switch case that allows the user to choose from 4 different options
			switch(count){
			case 0:
				//Display first choice
				displayLCDCenteredString(0, "Right");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button pressed
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count = 2;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			case 1:
				//Display first choice
				displayLCDCenteredString(0, "Left");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button press
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count--;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			case 2:
				//Display first choice
				displayLCDCenteredString(0, "Normal");
				displayLCDCenteredString(1, "<		 Enter		>");
				waitForPress();
				//Increment or decrement "count" based on button press
				if(nLCDButtons == leftButton)
				{
					waitForRelease();
					count--;
				}
				else if(nLCDButtons == rightButton)
				{
					waitForRelease();
					count++;
				}
				break;
			default:
				count = 0;
				break;
			}
			}
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/


task autonomous()
{
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice from pre_auton.
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Right");
		displayLCDCenteredString(1, "is running!");
		right();
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Left");
		displayLCDCenteredString(1, "is running!");
		left();
		break;
	case 2:
		displayLCDCenteredString(0, "Normal");
		displayLCDCenteredString(1, "is running!");
		normal();
		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	while(true)
	{
	  motor[driveR1R2] = vexRT[Ch2];
	  motor[driveR3] = vexRT[Ch2];
	  motor[driveR4] = vexRT[Ch2];
	  motor[driveL1L2] = vexRT[Ch3];
	  motor[driveL3] = vexRT[Ch3];
	  motor[driveL4] = vexRT[Ch3];


  if (vexRT[Btn6U] == 1)
		 {
		   int c = 127;
		   motor[armL] = c; //This motor will lift up with value c
		   motor[armR] = c;
		   motor[armX] = c;
		 }
	else if (vexRT[Btn6D] == 1)
		 {
		   int c = -127;

		   motor[armL] = c; //This motor will lift down with value c
		   motor[armR] = c;
		   motor[armX] = c;
	   }
	else
     {
       int L = 0;

       motor[armL] = L; //This motor will stop running
       motor[armR] = L;
       motor[armX] = L;
     }

  if (vexRT[Btn5D] == 1) //Front motor will turn inside
     {
       int y = 127;

       motor[claw] = y;
     }


  else if (vexRT[Btn5U] == 1) //Front motor will turn outside
     {
       int Y = 127;

       motor[claw] = -Y;
     }

  else // The motor will be stop
  	 {

  	   int L = 0;

  	   motor[claw] = L;
     }

  if (vexRT[Btn8U] == 1) // The motors will lock
     {
  	   int H = 20;

  	   motor[claw] = H;
     }
  }
}
  	// This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.
    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................
    // Remove this function call once you have "real" code.
    //UserControlCodePlaceholderForTesting();
